FROM node:latest as build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

# Copy the entire project to the working directory
COPY . .


RUN npm run build


FROM nginx:alpine

# Copy the build output from the build environment to the nginx server root
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

# Start nginx server
CMD ["nginx", "-g", "daemon off;"]
